spring:
  application:
    name: order
  server:
    port: 8080
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      group-id: order-group
      auto-offset-reset: earliest
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
